App\Module\Operations\Entity\ArrivalNotice:

    list:
        - id
        - shipment
        - issueDate
        - consigneeName
        - consigneeAddress
        - destinationChargesNote
        - requiredDocuments
        - note
        - createdDate
        - updatedDate

    detail:
        - id
        - shipment
        - issueDate
        - consigneeName
        - consigneeAddress
        - destinationChargesNote
        - requiredDocuments
        - note
        - createdDate
        - updatedDate
