App\Module\Operations\Entity\DeliveryOrder:

    list:
        - id
        - shipment
        - issueDate
        - consigneeName
        - consigneeAddress
        - releaseDate
        - releaseNote
        - note
        - createdDate
        - updatedDate

    detail:
        - id
        - shipment
        - issueDate
        - consigneeName
        - consigneeAddress
        - releaseDate
        - releaseNote
        - note
        - createdDate
        - updatedDate
