App\Module\Finance\Entity\EbitNote:

    list:
        - type
        - shipment
        - parentNote
        - id
        - code
        - codeReference
        - status
        - paymentMethod
        - collectFrom
        - payTo
        - amountNoTax
        - tax
        - amount
        - currency
        - createdBy
        - dueDate
        - noteDate
        - createdDate
        - fxGainLoss
        - varianceStatus
        - creditNoteReason
        - isLocked
        - vendorRef
        - approvedBy
        - approvedAt

    subList:
        - _extends:list
        - _exclude:shipment
