App\Module\Finance\Entity\ExchangeRateGroup:

    list:
        - id
        - exchangeRates
        - currency
        - createdBy
        - createdDate
    currentExchangeRates:
        - exchangeRates
        - currency