App\Module\Finance\Entity\ExchangeRate:

    list:
        - id
        - fromCurrency
        - toCurrency
        - fromRate
        - toRate
        - rate
    currentExchangeRates:
        - fromCurrency
        - toCurrency
        - fromRate
        - toRate
        - rate