App\Module\Tax\Entity\HsCode:

    list:
        - id
        - code
        - description
        - level
        - digits
        - countryCode
        - hsVersion
        - isActive
        - effectiveFrom
        - effectiveTo
        - parent

    detail:
        - id
        - code
        - description
        - level
        - digits
        - countryCode
        - hsVersion
        - isActive
        - effectiveFrom
        - effectiveTo
        - parent
