App\Module\Core\Entity\PackageType:

    list:
        - id
        - name
        - weight
        - height
        - length
        - width
        - createdBy
        - createdDate
        - description
