App\Module\Quote\Entity\Rate:

    list:
        - id
        - charge
        - buying
        - selling
        - provider
        - localChargePort
        - localChargeType
        - validFrom
        - validUntil
        - createdDate
        - createdBy
