App\Module\Carrier\Entity\TrackingEventRaw:

    list:
        - id
        - source
        - rawPayload
        - isProcessed
        - processedAt
        - error
        - receivedAt

    detail:
        - id
        - source
        - rawPayload
        - isProcessed
        - processedAt
        - error
        - receivedAt
