App\Module\Carrier\Entity\VesselRoll:

    list:
        - id
        - originalSailingRef
        - originalEtd
        - newSailingRef
        - newEtd
        - reason
        - notifiedAt
        - rolledAt
        - rolledBy
