<?php

declare(strict_types=1);

namespace CommonMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260728101914 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bank_account (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, bank_name VARCHAR(255) DEFAULT NULL, branch VARCHAR(255) DEFAULT NULL, swift_code VARCHAR(255) DEFAULT NULL, account_name VARCHAR(255) DEFAULT NULL, account_number VARCHAR(255) DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL)');
        $this->addSql('CREATE TABLE branch (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(50) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL)');
        $this->addSql('CREATE TABLE charge (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, created_by_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL, charge_type VARCHAR(255) NOT NULL, transport_type VARCHAR(255) NOT NULL, custom_calc_type VARCHAR(255) DEFAULT NULL, custom_code VARCHAR(255) DEFAULT NULL, description CLOB DEFAULT NULL, debit_tax NUMERIC(5, 2) DEFAULT NULL, credit_tax NUMERIC(5, 2) DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, CONSTRAINT FK_556BA434B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_556BA434B03A8386 ON charge (created_by_id)');
        $this->addSql('CREATE TABLE charge_item (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, charge_id INTEGER DEFAULT NULL, tax_group_id INTEGER DEFAULT NULL, ebit_note_id INTEGER NOT NULL, department_id INTEGER DEFAULT NULL, charge_name VARCHAR(255) NOT NULL, charge_type VARCHAR(255) DEFAULT NULL, charge_type_name VARCHAR(255) NOT NULL, calculation_type VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, quantity DOUBLE PRECISION DEFAULT NULL, provider_name VARCHAR(255) DEFAULT NULL, position INTEGER DEFAULT NULL, payable_at VARCHAR(16) DEFAULT NULL, visible_to VARCHAR(16) DEFAULT NULL, tax_code VARCHAR(16) DEFAULT NULL, tax_pct NUMERIC(6, 4) DEFAULT \'0.0000\' NOT NULL, is_zero_rated BOOLEAN DEFAULT 0 NOT NULL, is_exempt BOOLEAN DEFAULT 0 NOT NULL, is_reverse_charge BOOLEAN DEFAULT 0 NOT NULL, price_amount NUMERIC(15, 4) DEFAULT NULL, price_currency VARCHAR(255) DEFAULT NULL, price_rate NUMERIC(15, 6) DEFAULT NULL, tax_amount NUMERIC(15, 4) DEFAULT NULL, tax_currency VARCHAR(255) DEFAULT NULL, tax_rate NUMERIC(15, 6) DEFAULT NULL, charge_price_amount NUMERIC(15, 4) DEFAULT NULL, charge_price_currency VARCHAR(255) DEFAULT NULL, charge_price_rate NUMERIC(15, 6) DEFAULT NULL, amount_amount NUMERIC(15, 4) DEFAULT NULL, amount_currency VARCHAR(255) DEFAULT NULL, amount_rate NUMERIC(15, 6) DEFAULT NULL, expected_amount_amount NUMERIC(15, 4) DEFAULT NULL, expected_amount_currency VARCHAR(255) DEFAULT NULL, expected_amount_rate NUMERIC(15, 6) DEFAULT NULL, CONSTRAINT FK_57D848C155284914 FOREIGN KEY (charge_id) REFERENCES charge (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_57D848C11EC078F9 FOREIGN KEY (tax_group_id) REFERENCES tax_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_57D848C174A679AC FOREIGN KEY (ebit_note_id) REFERENCES ebit_note (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_57D848C1AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_57D848C155284914 ON charge_item (charge_id)');
        $this->addSql('CREATE INDEX IDX_57D848C11EC078F9 ON charge_item (tax_group_id)');
        $this->addSql('CREATE INDEX IDX_57D848C174A679AC ON charge_item (ebit_note_id)');
        $this->addSql('CREATE INDEX IDX_57D848C1AE80F5DF ON charge_item (department_id)');
        $this->addSql('CREATE TABLE chart_of_account (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, code VARCHAR(16) NOT NULL, name VARCHAR(128) NOT NULL, account_type VARCHAR(16) NOT NULL, is_active BOOLEAN NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_153C00DE77153098 ON chart_of_account (code)');
        $this->addSql('CREATE TABLE client (id INTEGER NOT NULL, default_invoice_info_id INTEGER NOT NULL, default_bank_account_id INTEGER NOT NULL, default_contact_id INTEGER NOT NULL, credit_reviewed_by_id INTEGER DEFAULT NULL, custom_info_id INTEGER DEFAULT NULL, created_by_id INTEGER NOT NULL, account_manager_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, province VARCHAR(255) DEFAULT NULL, zip_code VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, trading_name VARCHAR(255) DEFAULT NULL, tax_number VARCHAR(64) DEFAULT NULL, registration_no VARCHAR(64) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, is_active BOOLEAN NOT NULL, establishment_date DATETIME DEFAULT NULL, type VARCHAR(1) NOT NULL, tier VARCHAR(16) DEFAULT NULL, residence_type VARCHAR(1) DEFAULT NULL, note CLOB DEFAULT NULL, credit_period SMALLINT DEFAULT NULL, credit_status VARCHAR(16) NOT NULL, credit_hold_reason CLOB DEFAULT NULL, credit_reviewed_at DATE DEFAULT NULL, custom_info_mode VARCHAR(1) NOT NULL, code VARCHAR(255) DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, credit_limit_amount NUMERIC(15, 4) DEFAULT NULL, credit_limit_currency VARCHAR(255) DEFAULT NULL, credit_limit_rate NUMERIC(15, 6) DEFAULT NULL, unpaid_amount NUMERIC(15, 4) DEFAULT NULL, unpaid_currency VARCHAR(255) DEFAULT NULL, unpaid_rate NUMERIC(15, 6) DEFAULT NULL, PRIMARY KEY(id), CONSTRAINT FK_C744045537045FF7 FOREIGN KEY (default_invoice_info_id) REFERENCES invoice_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C74404558A9D31D0 FOREIGN KEY (default_bank_account_id) REFERENCES bank_account (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C7440455AF827129 FOREIGN KEY (default_contact_id) REFERENCES contact (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C7440455B9F59F1 FOREIGN KEY (credit_reviewed_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C74404555AD2A835 FOREIGN KEY (custom_info_id) REFERENCES invoice_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C7440455B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C744045584A5C6C7 FOREIGN KEY (account_manager_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C7440455BF396750 FOREIGN KEY (id) REFERENCES partner (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C744045537045FF7 ON client (default_invoice_info_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C74404558A9D31D0 ON client (default_bank_account_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C7440455AF827129 ON client (default_contact_id)');
        $this->addSql('CREATE INDEX IDX_C7440455B9F59F1 ON client (credit_reviewed_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C74404555AD2A835 ON client (custom_info_id)');
        $this->addSql('CREATE INDEX IDX_C7440455B03A8386 ON client (created_by_id)');
        $this->addSql('CREATE INDEX IDX_C744045584A5C6C7 ON client (account_manager_id)');
        $this->addSql('CREATE TABLE client_invoice_info (client_id INTEGER NOT NULL, invoice_info_id INTEGER NOT NULL, PRIMARY KEY(client_id, invoice_info_id), CONSTRAINT FK_7846F13319EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_7846F133AF52F72B FOREIGN KEY (invoice_info_id) REFERENCES invoice_info (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_7846F13319EB6921 ON client_invoice_info (client_id)');
        $this->addSql('CREATE INDEX IDX_7846F133AF52F72B ON client_invoice_info (invoice_info_id)');
        $this->addSql('CREATE TABLE client_bank_account (client_id INTEGER NOT NULL, bank_account_id INTEGER NOT NULL, PRIMARY KEY(client_id, bank_account_id), CONSTRAINT FK_E2A89C0B19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E2A89C0B12CB990C FOREIGN KEY (bank_account_id) REFERENCES bank_account (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_E2A89C0B19EB6921 ON client_bank_account (client_id)');
        $this->addSql('CREATE INDEX IDX_E2A89C0B12CB990C ON client_bank_account (bank_account_id)');
        $this->addSql('CREATE TABLE client_contact (client_id INTEGER NOT NULL, contact_id INTEGER NOT NULL, PRIMARY KEY(client_id, contact_id), CONSTRAINT FK_1E5FA24519EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_1E5FA245E7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_1E5FA24519EB6921 ON client_contact (client_id)');
        $this->addSql('CREATE INDEX IDX_1E5FA245E7A1254A ON client_contact (contact_id)');
        $this->addSql('CREATE TABLE client_media (client_id INTEGER NOT NULL, media_id INTEGER NOT NULL, PRIMARY KEY(client_id, media_id), CONSTRAINT FK_C9413DBB19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C9413DBBEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_C9413DBB19EB6921 ON client_media (client_id)');
        $this->addSql('CREATE INDEX IDX_C9413DBBEA9FDD75 ON client_media (media_id)');
        $this->addSql('CREATE TABLE client_user (client_id INTEGER NOT NULL, user_id INTEGER NOT NULL, PRIMARY KEY(client_id, user_id), CONSTRAINT FK_5C0F152B19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_5C0F152BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_5C0F152B19EB6921 ON client_user (client_id)');
        $this->addSql('CREATE INDEX IDX_5C0F152BA76ED395 ON client_user (user_id)');
        $this->addSql('CREATE TABLE component (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, dataset_id INTEGER DEFAULT NULL, page_id INTEGER NOT NULL, filters CLOB DEFAULT NULL --(DC2Type:json)
        , row_number INTEGER NOT NULL, order_number INTEGER NOT NULL, column_width INTEGER NOT NULL, type VARCHAR(255) NOT NULL, title VARCHAR(255) DEFAULT NULL, series CLOB DEFAULT NULL, stacked BOOLEAN DEFAULT NULL, CONSTRAINT FK_49FEA157D47C2D1B FOREIGN KEY (dataset_id) REFERENCES dataset (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_49FEA157C4663E4 FOREIGN KEY (page_id) REFERENCES page (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_49FEA157D47C2D1B ON component (dataset_id)');
        $this->addSql('CREATE INDEX IDX_49FEA157C4663E4 ON component (page_id)');
        $this->addSql('CREATE TABLE config (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) NOT NULL, value VARCHAR(255) DEFAULT NULL, type VARCHAR(255) NOT NULL)');
        $this->addSql('CREATE TABLE contact (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, department VARCHAR(255) DEFAULT NULL, date_of_birth DATETIME DEFAULT NULL, gender VARCHAR(255) DEFAULT NULL, salutation VARCHAR(16) DEFAULT NULL, mobile VARCHAR(32) DEFAULT NULL, whatsapp VARCHAR(32) DEFAULT NULL, language VARCHAR(2) NOT NULL, is_active BOOLEAN NOT NULL, receives_invoice BOOLEAN NOT NULL, receives_tracking BOOLEAN NOT NULL, receives_arrival BOOLEAN NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL)');
        $this->addSql('CREATE TABLE credit_limit_history (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, client_id INTEGER NOT NULL, changed_by_id INTEGER DEFAULT NULL, change_type VARCHAR(32) NOT NULL, old_status VARCHAR(16) DEFAULT NULL, new_status VARCHAR(16) DEFAULT NULL, old_limit_amount NUMERIC(15, 4) DEFAULT NULL, new_limit_amount NUMERIC(15, 4) DEFAULT NULL, currency VARCHAR(8) DEFAULT NULL, reason CLOB DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, CONSTRAINT FK_95C4062919EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_95C40629828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_95C4062919EB6921 ON credit_limit_history (client_id)');
        $this->addSql('CREATE INDEX IDX_95C40629828AD0A0 ON credit_limit_history (changed_by_id)');
        $this->addSql('CREATE TABLE crm_activity (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, opportunity_id INTEGER DEFAULT NULL, client_id INTEGER DEFAULT NULL, performed_by_id INTEGER DEFAULT NULL, activity_type VARCHAR(32) NOT NULL, subject VARCHAR(255) DEFAULT NULL, description CLOB DEFAULT NULL, outcome VARCHAR(32) DEFAULT NULL, next_action CLOB DEFAULT NULL, next_action_date DATE DEFAULT NULL, performed_at DATETIME NOT NULL, CONSTRAINT FK_C2F344F19A34590F FOREIGN KEY (opportunity_id) REFERENCES crm_opportunity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C2F344F119EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C2F344F12E65C292 FOREIGN KEY (performed_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_C2F344F19A34590F ON crm_activity (opportunity_id)');
        $this->addSql('CREATE INDEX IDX_C2F344F119EB6921 ON crm_activity (client_id)');
        $this->addSql('CREATE INDEX IDX_C2F344F12E65C292 ON crm_activity (performed_by_id)');
        $this->addSql('CREATE TABLE crm_lead (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, assigned_to_id INTEGER DEFAULT NULL, created_by_id INTEGER DEFAULT NULL, converted_client_id INTEGER DEFAULT NULL, company_name VARCHAR(255) NOT NULL, contact_name VARCHAR(128) DEFAULT NULL, contact_email VARCHAR(128) DEFAULT NULL, contact_phone VARCHAR(32) DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, industry VARCHAR(64) DEFAULT NULL, estimated_volume VARCHAR(32) DEFAULT NULL, primary_mode VARCHAR(8) DEFAULT NULL, primary_trade VARCHAR(64) DEFAULT NULL, source VARCHAR(32) DEFAULT NULL, status VARCHAR(16) NOT NULL, converted_at DATETIME DEFAULT NULL, notes CLOB DEFAULT NULL, created_at DATETIME NOT NULL, CONSTRAINT FK_474D437AF4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_474D437AB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_474D437A5AA408DD FOREIGN KEY (converted_client_id) REFERENCES client (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_474D437AF4BD7827 ON crm_lead (assigned_to_id)');
        $this->addSql('CREATE INDEX IDX_474D437AB03A8386 ON crm_lead (created_by_id)');
        $this->addSql('CREATE INDEX IDX_474D437A5AA408DD ON crm_lead (converted_client_id)');
        $this->addSql('CREATE TABLE crm_opportunity (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, lead_id INTEGER DEFAULT NULL, client_id INTEGER DEFAULT NULL, assigned_to_id INTEGER DEFAULT NULL, title VARCHAR(255) NOT NULL, transport_mode VARCHAR(8) DEFAULT NULL, service_type VARCHAR(16) DEFAULT NULL, pol_name VARCHAR(64) DEFAULT NULL, pod_name VARCHAR(64) DEFAULT NULL, estimated_volume NUMERIC(10, 2) DEFAULT NULL, volume_uom VARCHAR(8) DEFAULT NULL, estimated_revenue NUMERIC(20, 6) DEFAULT NULL, currency VARCHAR(3) DEFAULT NULL, stage VARCHAR(32) NOT NULL, probability_pct SMALLINT NOT NULL, expected_close DATE DEFAULT NULL, competitor VARCHAR(128) DEFAULT NULL, loss_reason VARCHAR(64) DEFAULT NULL, win_reason VARCHAR(64) DEFAULT NULL, quote_id INTEGER DEFAULT NULL, notes CLOB DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, closed_at DATETIME DEFAULT NULL, CONSTRAINT FK_60AF56F355458D FOREIGN KEY (lead_id) REFERENCES crm_lead (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_60AF56F319EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_60AF56F3F4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_60AF56F355458D ON crm_opportunity (lead_id)');
        $this->addSql('CREATE INDEX IDX_60AF56F319EB6921 ON crm_opportunity (client_id)');
        $this->addSql('CREATE INDEX IDX_60AF56F3F4BD7827 ON crm_opportunity (assigned_to_id)');
        $this->addSql('CREATE TABLE currency (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) NOT NULL, symbol VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, rate DOUBLE PRECISION DEFAULT NULL, thousand_separator VARCHAR(10) DEFAULT NULL, decimal_separator VARCHAR(10) DEFAULT NULL, decimal_places INTEGER DEFAULT NULL)');
        $this->addSql('CREATE TABLE customer_tax_exemption (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, partner_id INTEGER NOT NULL, verified_by_id INTEGER DEFAULT NULL, exemption_type VARCHAR(32) NOT NULL, country_code VARCHAR(2) NOT NULL, exemption_ref VARCHAR(64) DEFAULT NULL, valid_from DATE NOT NULL, valid_to DATE DEFAULT NULL, document_url CLOB DEFAULT NULL, verified_at DATE DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, CONSTRAINT FK_B81643139393F8FE FOREIGN KEY (partner_id) REFERENCES partner (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_B816431369F4B775 FOREIGN KEY (verified_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_B81643139393F8FE ON customer_tax_exemption (partner_id)');
        $this->addSql('CREATE INDEX IDX_B816431369F4B775 ON customer_tax_exemption (verified_by_id)');
        $this->addSql('CREATE TABLE customs_entry (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, shipment_id INTEGER DEFAULT NULL, entry_type VARCHAR(16) NOT NULL, entry_mode VARCHAR(32) DEFAULT NULL, declaration_number VARCHAR(64) DEFAULT NULL, entry_number VARCHAR(64) DEFAULT NULL, status VARCHAR(32) NOT NULL, customs_office VARCHAR(64) DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, system_code VARCHAR(32) DEFAULT NULL, cif_value NUMERIC(20, 6) DEFAULT NULL, value_currency VARCHAR(3) DEFAULT NULL, total_duty NUMERIC(20, 6) DEFAULT NULL, total_vat NUMERIC(20, 6) DEFAULT NULL, total_tax NUMERIC(20, 6) DEFAULT NULL, submitted_at DATETIME DEFAULT NULL, acknowledged_at DATETIME DEFAULT NULL, released_at DATETIME DEFAULT NULL, submission_ref VARCHAR(128) DEFAULT NULL, notes CLOB DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL)');
        $this->addSql('CREATE TABLE customs_entry_line (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, customs_entry_id INTEGER NOT NULL, line_number SMALLINT NOT NULL, hs_code VARCHAR(12) DEFAULT NULL, description CLOB DEFAULT NULL, country_of_origin VARCHAR(2) DEFAULT NULL, packages INTEGER DEFAULT NULL, net_weight_kg NUMERIC(12, 3) DEFAULT NULL, gross_weight_kg NUMERIC(12, 3) DEFAULT NULL, quantity NUMERIC(12, 4) DEFAULT NULL, uom VARCHAR(16) DEFAULT NULL, unit_price NUMERIC(20, 6) DEFAULT NULL, line_value NUMERIC(20, 6) DEFAULT NULL, value_currency VARCHAR(3) DEFAULT NULL, duty_rate NUMERIC(6, 4) DEFAULT NULL, duty_amount NUMERIC(20, 6) DEFAULT NULL, vat_rate NUMERIC(6, 4) DEFAULT NULL, vat_amount NUMERIC(20, 6) DEFAULT NULL, is_restricted BOOLEAN NOT NULL, CONSTRAINT FK_3D7A1F2E8BAD98DA FOREIGN KEY (customs_entry_id) REFERENCES customs_entry (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_3D7A1F2E8BAD98DA ON customs_entry_line (customs_entry_id)');
        $this->addSql('CREATE TABLE dataset (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, created_by_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL, entity_type VARCHAR(255) NOT NULL, filters CLOB DEFAULT NULL, columns CLOB DEFAULT NULL --(DC2Type:simple_array)
        , stats CLOB DEFAULT NULL --(DC2Type:simple_array)
        , row_type VARCHAR(255) NOT NULL, group_column VARCHAR(255) DEFAULT NULL, date_segment VARCHAR(255) DEFAULT NULL, order_number INTEGER DEFAULT NULL, currency VARCHAR(255) DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, CONSTRAINT FK_B7A041D0B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_B7A041D0B03A8386 ON dataset (created_by_id)');
        $this->addSql('CREATE TABLE department (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, branch_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL, direction VARCHAR(5) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, CONSTRAINT FK_CD1DE18ADCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_CD1DE18ADCD6CC49 ON department (branch_id)');
        $this->addSql('CREATE TABLE duty_rate (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, hs_code_id INTEGER NOT NULL, import_country VARCHAR(2) DEFAULT NULL, export_country VARCHAR(2) DEFAULT NULL, rate_type VARCHAR(50) DEFAULT NULL, fta_name VARCHAR(100) DEFAULT NULL, duty_rate NUMERIC(10, 4) DEFAULT NULL, vat_rate NUMERIC(10, 4) DEFAULT NULL, excise_rate NUMERIC(10, 4) DEFAULT NULL, effective_from DATE DEFAULT NULL, effective_to DATE DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, CONSTRAINT FK_73D74BFCDE2413E1 FOREIGN KEY (hs_code_id) REFERENCES hs_code (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_73D74BFCDE2413E1 ON duty_rate (hs_code_id)');
        $this->addSql('CREATE TABLE ebit_note (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, payment_method_id INTEGER DEFAULT NULL, collect_from_id INTEGER DEFAULT NULL, pay_to_id INTEGER DEFAULT NULL, created_by_id INTEGER NOT NULL, invoice_info_id INTEGER DEFAULT NULL, parent_note_id INTEGER DEFAULT NULL, approved_by_id INTEGER DEFAULT NULL, code VARCHAR(255) NOT NULL, due_date DATETIME NOT NULL, currency VARCHAR(255) NOT NULL, container_no CLOB DEFAULT NULL --(DC2Type:simple_array)
        , seal_no CLOB DEFAULT NULL --(DC2Type:simple_array)
        , show_one_currency BOOLEAN DEFAULT NULL, note CLOB DEFAULT NULL, note_date DATETIME DEFAULT NULL, exchange_rates CLOB NOT NULL --(DC2Type:json)
        , type VARCHAR(255) NOT NULL, target_type VARCHAR(255) DEFAULT NULL, money_scale SMALLINT NOT NULL, status VARCHAR(255) NOT NULL, shipment_id INTEGER DEFAULT NULL, pic VARCHAR(255) DEFAULT NULL, amount_in_words VARCHAR(255) DEFAULT NULL, description CLOB DEFAULT NULL, code_reference VARCHAR(255) DEFAULT NULL, fx_gain_loss NUMERIC(15, 4) DEFAULT NULL, variance_status VARCHAR(16) DEFAULT NULL, credit_note_reason VARCHAR(32) DEFAULT NULL, is_locked BOOLEAN NOT NULL, vendor_ref VARCHAR(64) DEFAULT NULL, approved_at DATETIME DEFAULT NULL, withholding_tax_rate NUMERIC(6, 4) DEFAULT NULL, withholding_tax_amount NUMERIC(20, 6) DEFAULT NULL, withholding_tax_ref VARCHAR(64) DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, amount_no_tax_amount NUMERIC(15, 4) DEFAULT NULL, amount_no_tax_currency VARCHAR(255) DEFAULT NULL, amount_no_tax_rate NUMERIC(15, 6) DEFAULT NULL, amount_amount NUMERIC(15, 4) DEFAULT NULL, amount_currency VARCHAR(255) DEFAULT NULL, amount_rate NUMERIC(15, 6) DEFAULT NULL, tax_amount NUMERIC(15, 4) DEFAULT NULL, tax_currency VARCHAR(255) DEFAULT NULL, tax_rate NUMERIC(15, 6) DEFAULT NULL, CONSTRAINT FK_B8144C705AA1164F FOREIGN KEY (payment_method_id) REFERENCES payment_method (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_B8144C703870A541 FOREIGN KEY (collect_from_id) REFERENCES partner (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_B8144C7078D4E5FC FOREIGN KEY (pay_to_id) REFERENCES partner (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_B8144C70B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_B8144C70AF52F72B FOREIGN KEY (invoice_info_id) REFERENCES invoice_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_B8144C7054A57C13 FOREIGN KEY (parent_note_id) REFERENCES ebit_note (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_B8144C702D234F6A FOREIGN KEY (approved_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_B8144C705AA1164F ON ebit_note (payment_method_id)');
        $this->addSql('CREATE INDEX IDX_B8144C703870A541 ON ebit_note (collect_from_id)');
        $this->addSql('CREATE INDEX IDX_B8144C7078D4E5FC ON ebit_note (pay_to_id)');
        $this->addSql('CREATE INDEX IDX_B8144C70B03A8386 ON ebit_note (created_by_id)');
        $this->addSql('CREATE INDEX IDX_B8144C70AF52F72B ON ebit_note (invoice_info_id)');
        $this->addSql('CREATE INDEX IDX_B8144C7054A57C13 ON ebit_note (parent_note_id)');
        $this->addSql('CREATE INDEX IDX_B8144C702D234F6A ON ebit_note (approved_by_id)');
        $this->addSql('CREATE TABLE ebit_note_media (ebit_note_id INTEGER NOT NULL, media_id INTEGER NOT NULL, PRIMARY KEY(ebit_note_id, media_id), CONSTRAINT FK_62039A7974A679AC FOREIGN KEY (ebit_note_id) REFERENCES ebit_note (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_62039A79EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_62039A7974A679AC ON ebit_note_media (ebit_note_id)');
        $this->addSql('CREATE INDEX IDX_62039A79EA9FDD75 ON ebit_note_media (media_id)');
        $this->addSql('CREATE TABLE exchange_rate (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, exchange_rate_group_id INTEGER NOT NULL, from_currency_id INTEGER NOT NULL, to_currency_id INTEGER NOT NULL, from_rate DOUBLE PRECISION NOT NULL, to_rate DOUBLE PRECISION NOT NULL, rate DOUBLE PRECISION NOT NULL, CONSTRAINT FK_E9521FAB96FF1145 FOREIGN KEY (exchange_rate_group_id) REFERENCES exchange_rate_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E9521FABA66BB013 FOREIGN KEY (from_currency_id) REFERENCES currency (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E9521FAB16B7BF15 FOREIGN KEY (to_currency_id) REFERENCES currency (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_E9521FAB96FF1145 ON exchange_rate (exchange_rate_group_id)');
        $this->addSql('CREATE INDEX IDX_E9521FABA66BB013 ON exchange_rate (from_currency_id)');
        $this->addSql('CREATE INDEX IDX_E9521FAB16B7BF15 ON exchange_rate (to_currency_id)');
        $this->addSql('CREATE TABLE exchange_rate_group (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, created_by_id INTEGER NOT NULL, currency_id INTEGER NOT NULL, is_default BOOLEAN DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, CONSTRAINT FK_B1A46521B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_B1A4652138248176 FOREIGN KEY (currency_id) REFERENCES currency (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_B1A46521B03A8386 ON exchange_rate_group (created_by_id)');
        $this->addSql('CREATE INDEX IDX_B1A4652138248176 ON exchange_rate_group (currency_id)');
        $this->addSql('CREATE TABLE hs_code (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, parent_id INTEGER DEFAULT NULL, code VARCHAR(10) NOT NULL, description VARCHAR(500) NOT NULL, level INTEGER DEFAULT NULL, digits INTEGER DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, hs_version VARCHAR(10) DEFAULT NULL, is_active BOOLEAN DEFAULT 1 NOT NULL, effective_from DATE DEFAULT NULL, effective_to DATE DEFAULT NULL, CONSTRAINT FK_4491150D727ACA70 FOREIGN KEY (parent_id) REFERENCES hs_code (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_4491150D727ACA70 ON hs_code (parent_id)');
        $this->addSql('CREATE TABLE hs_restriction (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, hs_code_id INTEGER NOT NULL, country_code VARCHAR(2) DEFAULT NULL, restriction_type VARCHAR(50) DEFAULT NULL, authority VARCHAR(255) DEFAULT NULL, licence_type VARCHAR(100) DEFAULT NULL, effective_from DATE DEFAULT NULL, effective_to DATE DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, CONSTRAINT FK_36F017CDDE2413E1 FOREIGN KEY (hs_code_id) REFERENCES hs_code (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_36F017CDDE2413E1 ON hs_restriction (hs_code_id)');
        $this->addSql('CREATE TABLE hs_version_mapping (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, old_hs_code_id INTEGER NOT NULL, new_hs_code_id INTEGER NOT NULL, old_version VARCHAR(10) DEFAULT NULL, new_version VARCHAR(10) DEFAULT NULL, change_type VARCHAR(50) DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, CONSTRAINT FK_84E05981620724BF FOREIGN KEY (old_hs_code_id) REFERENCES hs_code (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_84E0598131BF02D FOREIGN KEY (new_hs_code_id) REFERENCES hs_code (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_84E05981620724BF ON hs_version_mapping (old_hs_code_id)');
        $this->addSql('CREATE INDEX IDX_84E0598131BF02D ON hs_version_mapping (new_hs_code_id)');
        $this->addSql('CREATE TABLE in_app_notification (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, rule_key VARCHAR(64) DEFAULT NULL, title VARCHAR(255) NOT NULL, body CLOB NOT NULL, priority VARCHAR(8) NOT NULL, is_read BOOLEAN NOT NULL, read_at DATETIME DEFAULT NULL, action_url CLOB DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, CONSTRAINT FK_8CD5FC15A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_8CD5FC15A76ED395 ON in_app_notification (user_id)');
        $this->addSql('CREATE TABLE invoice_info (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, bank_account_id INTEGER DEFAULT NULL, company VARCHAR(255) NOT NULL, phone VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, contact_name VARCHAR(255) DEFAULT NULL, tax_number VARCHAR(255) DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, CONSTRAINT FK_C94C533212CB990C FOREIGN KEY (bank_account_id) REFERENCES bank_account (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_C94C533212CB990C ON invoice_info (bank_account_id)');
        $this->addSql('CREATE TABLE journal_entry (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ebit_note_id INTEGER DEFAULT NULL, posted_by_id INTEGER DEFAULT NULL, journal_number VARCHAR(64) NOT NULL, source_type VARCHAR(32) NOT NULL, entry_date DATE NOT NULL, description CLOB DEFAULT NULL, is_posted BOOLEAN NOT NULL, posted_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, CONSTRAINT FK_C8FAAE5A74A679AC FOREIGN KEY (ebit_note_id) REFERENCES ebit_note (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C8FAAE5A5A6D2235 FOREIGN KEY (posted_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C8FAAE5A4DC80DB1 ON journal_entry (journal_number)');
        $this->addSql('CREATE INDEX IDX_C8FAAE5A74A679AC ON journal_entry (ebit_note_id)');
        $this->addSql('CREATE INDEX IDX_C8FAAE5A5A6D2235 ON journal_entry (posted_by_id)');
        $this->addSql('CREATE TABLE journal_line (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, journal_entry_id INTEGER NOT NULL, account_id INTEGER NOT NULL, debit NUMERIC(15, 4) NOT NULL, credit NUMERIC(15, 4) NOT NULL, currency VARCHAR(8) NOT NULL, base_debit NUMERIC(15, 4) NOT NULL, base_credit NUMERIC(15, 4) NOT NULL, fx_rate NUMERIC(15, 6) NOT NULL, description CLOB DEFAULT NULL, CONSTRAINT FK_692C8C7E6A86E4FB FOREIGN KEY (journal_entry_id) REFERENCES journal_entry (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_692C8C7E9B6B5FBA FOREIGN KEY (account_id) REFERENCES chart_of_account (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_692C8C7E6A86E4FB ON journal_line (journal_entry_id)');
        $this->addSql('CREATE INDEX IDX_692C8C7E9B6B5FBA ON journal_line (account_id)');
        $this->addSql('CREATE TABLE log (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_agent_id INTEGER DEFAULT NULL, created_date DATETIME DEFAULT NULL, user_id INTEGER DEFAULT NULL, ip VARCHAR(255) DEFAULT NULL, result SMALLINT DEFAULT NULL, response CLOB DEFAULT NULL, size INTEGER DEFAULT NULL, request CLOB DEFAULT NULL --(DC2Type:json)
        , response_time SMALLINT DEFAULT NULL, url CLOB DEFAULT NULL, exception CLOB DEFAULT NULL, method VARCHAR(255) DEFAULT NULL)');
        $this->addSql('CREATE TABLE mail (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, created_by_id INTEGER NOT NULL, from_address VARCHAR(255) NOT NULL, to_address VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, log CLOB DEFAULT NULL, parent_type VARCHAR(255) DEFAULT NULL, parent_id VARCHAR(255) DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, CONSTRAINT FK_5126AC48B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_5126AC48B03A8386 ON mail (created_by_id)');
        $this->addSql('CREATE TABLE media (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(5) NOT NULL, path VARCHAR(255) NOT NULL, size INTEGER NOT NULL, has_webp BOOLEAN DEFAULT NULL, has_thumb BOOLEAN DEFAULT NULL, created_by INTEGER DEFAULT NULL, created_date DATETIME NOT NULL, duration SMALLINT DEFAULT NULL, width SMALLINT DEFAULT NULL, height SMALLINT DEFAULT NULL, parent_type VARCHAR(255) DEFAULT NULL, parent_id INTEGER DEFAULT NULL, parent_property VARCHAR(255) DEFAULT NULL, language VARCHAR(255) DEFAULT NULL, note CLOB DEFAULT NULL, mime VARCHAR(255) DEFAULT NULL, category VARCHAR(255) DEFAULT NULL, s3_success BOOLEAN DEFAULT NULL, backup_success BOOLEAN DEFAULT NULL)');
        $this->addSql('CREATE TABLE notification_queue (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, rule_key VARCHAR(64) DEFAULT NULL, recipient_type VARCHAR(32) NOT NULL, recipient_id INTEGER DEFAULT NULL, recipient_email VARCHAR(128) DEFAULT NULL, channel VARCHAR(16) NOT NULL, subject VARCHAR(255) DEFAULT NULL, body CLOB NOT NULL, priority VARCHAR(8) NOT NULL, scheduled_at DATETIME NOT NULL, sent_at DATETIME DEFAULT NULL, status VARCHAR(16) NOT NULL, attempt_count INTEGER NOT NULL, last_error CLOB DEFAULT NULL, provider_ref VARCHAR(128) DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL)');
        $this->addSql('CREATE TABLE notification_rule (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, rule_key VARCHAR(64) NOT NULL, name VARCHAR(128) NOT NULL, trigger_type VARCHAR(32) NOT NULL, trigger_config CLOB NOT NULL --(DC2Type:json)
        , recipient_config CLOB NOT NULL --(DC2Type:json)
        , channels CLOB NOT NULL --(DC2Type:json)
        , template_key VARCHAR(64) DEFAULT NULL, is_active BOOLEAN NOT NULL, scope_type VARCHAR(16) NOT NULL, priority VARCHAR(8) NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FEE4E7F6FD5CEC5B ON notification_rule (rule_key)');
        $this->addSql('CREATE TABLE notification_template (key_col VARCHAR(64) NOT NULL, name VARCHAR(128) NOT NULL, channel VARCHAR(16) NOT NULL, subject_template VARCHAR(255) DEFAULT NULL, body_template CLOB NOT NULL, language VARCHAR(2) NOT NULL, variables CLOB DEFAULT NULL --(DC2Type:json)
        , PRIMARY KEY(key_col))');
        $this->addSql('CREATE TABLE organisation_address (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, client_id INTEGER DEFAULT NULL, address_type VARCHAR(32) NOT NULL, label VARCHAR(64) DEFAULT NULL, address_line1 VARCHAR(255) NOT NULL, address_line2 VARCHAR(255) DEFAULT NULL, city VARCHAR(128) NOT NULL, state VARCHAR(128) DEFAULT NULL, postal_code VARCHAR(32) DEFAULT NULL, country VARCHAR(2) NOT NULL, is_default BOOLEAN NOT NULL, notes CLOB DEFAULT NULL, created_at DATETIME NOT NULL, CONSTRAINT FK_6ECA188219EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_6ECA188219EB6921 ON organisation_address (client_id)');
        $this->addSql('CREATE TABLE page (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) NOT NULL, order_number INTEGER DEFAULT NULL, type VARCHAR(255) NOT NULL)');
        $this->addSql('CREATE TABLE partner (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, discr VARCHAR(255) NOT NULL)');
        $this->addSql('CREATE TABLE partner_tax_registration (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, partner_id INTEGER NOT NULL, country_code VARCHAR(2) NOT NULL, tax_type VARCHAR(16) NOT NULL, registration_no VARCHAR(64) NOT NULL, is_primary BOOLEAN NOT NULL, effective_from DATE NOT NULL, effective_to DATE DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, CONSTRAINT FK_5A4ED1149393F8FE FOREIGN KEY (partner_id) REFERENCES partner (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_5A4ED1149393F8FE ON partner_tax_registration (partner_id)');
        $this->addSql('CREATE TABLE payment_method (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, created_by_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, description CLOB DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, CONSTRAINT FK_7B61A1F6B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_7B61A1F6B03A8386 ON payment_method (created_by_id)');
        $this->addSql('CREATE TABLE sales_target (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, sales_rep_id INTEGER NOT NULL, branch_id INTEGER DEFAULT NULL, period_year SMALLINT NOT NULL, period_month SMALLINT DEFAULT NULL, target_type VARCHAR(32) NOT NULL, target_value NUMERIC(20, 6) NOT NULL, currency VARCHAR(3) DEFAULT NULL, created_at DATETIME NOT NULL, CONSTRAINT FK_649B7DF476311BE2 FOREIGN KEY (sales_rep_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_649B7DF4DCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_649B7DF476311BE2 ON sales_target (sales_rep_id)');
        $this->addSql('CREATE INDEX IDX_649B7DF4DCD6CC49 ON sales_target (branch_id)');
        $this->addSql('CREATE TABLE tax_group (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, created_by_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL, amount DOUBLE PRECISION NOT NULL, description CLOB DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, CONSTRAINT FK_DEBAB1E4B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_DEBAB1E4B03A8386 ON tax_group (created_by_id)');
        $this->addSql('CREATE TABLE tax_rule (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, country_code VARCHAR(2) NOT NULL, charge_category VARCHAR(16) DEFAULT NULL, service_type VARCHAR(16) DEFAULT NULL, customer_type VARCHAR(32) DEFAULT NULL, tax_type VARCHAR(16) NOT NULL, tax_code VARCHAR(16) NOT NULL, tax_rate NUMERIC(6, 4) NOT NULL, is_reverse_charge BOOLEAN NOT NULL, is_zero_rated BOOLEAN NOT NULL, is_exempt BOOLEAN NOT NULL, description VARCHAR(128) DEFAULT NULL, effective_from DATE NOT NULL, effective_to DATE DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL)');
        $this->addSql('CREATE TABLE "user" (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_group_id INTEGER NOT NULL, logo_id INTEGER DEFAULT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, roles CLOB NOT NULL --(DC2Type:json)
        , status VARCHAR(1) NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, phone VARCHAR(255) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, last_ping DATETIME DEFAULT NULL, last_view_module CLOB DEFAULT NULL --(DC2Type:json)
        , table_config CLOB DEFAULT NULL --(DC2Type:json)
        , language VARCHAR(10) DEFAULT \'en\' NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, CONSTRAINT FK_8D93D6491ED93D47 FOREIGN KEY (user_group_id) REFERENCES user_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_8D93D649F98F144A FOREIGN KEY (logo_id) REFERENCES media (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_8D93D6491ED93D47 ON "user" (user_group_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F98F144A ON "user" (logo_id)');
        $this->addSql('CREATE TABLE user_branch (user_id INTEGER NOT NULL, branch_id INTEGER NOT NULL, PRIMARY KEY(user_id, branch_id), CONSTRAINT FK_DED40022A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_DED40022DCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_DED40022A76ED395 ON user_branch (user_id)');
        $this->addSql('CREATE INDEX IDX_DED40022DCD6CC49 ON user_branch (branch_id)');
        $this->addSql('CREATE TABLE user_department (user_id INTEGER NOT NULL, department_id INTEGER NOT NULL, PRIMARY KEY(user_id, department_id), CONSTRAINT FK_6A7A2766A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_6A7A2766AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_6A7A2766A76ED395 ON user_department (user_id)');
        $this->addSql('CREATE INDEX IDX_6A7A2766AE80F5DF ON user_department (department_id)');
        $this->addSql('CREATE TABLE user_agent (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name CLOB NOT NULL)');
        $this->addSql('CREATE TABLE user_group (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, permissions CLOB DEFAULT NULL --(DC2Type:simple_array)
        )');
        $this->addSql('CREATE TABLE user_notification_preference (rule_key VARCHAR(64) NOT NULL, channel VARCHAR(16) NOT NULL, user_id INTEGER NOT NULL, is_enabled BOOLEAN NOT NULL, digest_mode BOOLEAN NOT NULL, digest_time VARCHAR(5) DEFAULT NULL, PRIMARY KEY(user_id, rule_key, channel), CONSTRAINT FK_1FCABC20A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_1FCABC20A76ED395 ON user_notification_preference (user_id)');
        $this->addSql('CREATE TABLE user_token (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, token VARCHAR(255) NOT NULL, expires_at INTEGER DEFAULT 0 NOT NULL, tags CLOB DEFAULT NULL --(DC2Type:simple_array)
        , nullified BOOLEAN DEFAULT 0 NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, CONSTRAINT FK_BDF55A63A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_BDF55A63A76ED395 ON user_token (user_id)');
        $this->addSql('CREATE TABLE messenger_messages (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, body CLOB NOT NULL, headers CLOB NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
        , available_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
        , delivered_at DATETIME DEFAULT NULL --(DC2Type:datetime_immutable)
        )');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE bank_account');
        $this->addSql('DROP TABLE branch');
        $this->addSql('DROP TABLE charge');
        $this->addSql('DROP TABLE charge_item');
        $this->addSql('DROP TABLE chart_of_account');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE client_invoice_info');
        $this->addSql('DROP TABLE client_bank_account');
        $this->addSql('DROP TABLE client_contact');
        $this->addSql('DROP TABLE client_media');
        $this->addSql('DROP TABLE client_user');
        $this->addSql('DROP TABLE component');
        $this->addSql('DROP TABLE config');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE credit_limit_history');
        $this->addSql('DROP TABLE crm_activity');
        $this->addSql('DROP TABLE crm_lead');
        $this->addSql('DROP TABLE crm_opportunity');
        $this->addSql('DROP TABLE currency');
        $this->addSql('DROP TABLE customer_tax_exemption');
        $this->addSql('DROP TABLE customs_entry');
        $this->addSql('DROP TABLE customs_entry_line');
        $this->addSql('DROP TABLE dataset');
        $this->addSql('DROP TABLE department');
        $this->addSql('DROP TABLE duty_rate');
        $this->addSql('DROP TABLE ebit_note');
        $this->addSql('DROP TABLE ebit_note_media');
        $this->addSql('DROP TABLE exchange_rate');
        $this->addSql('DROP TABLE exchange_rate_group');
        $this->addSql('DROP TABLE hs_code');
        $this->addSql('DROP TABLE hs_restriction');
        $this->addSql('DROP TABLE hs_version_mapping');
        $this->addSql('DROP TABLE in_app_notification');
        $this->addSql('DROP TABLE invoice_info');
        $this->addSql('DROP TABLE journal_entry');
        $this->addSql('DROP TABLE journal_line');
        $this->addSql('DROP TABLE log');
        $this->addSql('DROP TABLE mail');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE notification_queue');
        $this->addSql('DROP TABLE notification_rule');
        $this->addSql('DROP TABLE notification_template');
        $this->addSql('DROP TABLE organisation_address');
        $this->addSql('DROP TABLE page');
        $this->addSql('DROP TABLE partner');
        $this->addSql('DROP TABLE partner_tax_registration');
        $this->addSql('DROP TABLE payment_method');
        $this->addSql('DROP TABLE sales_target');
        $this->addSql('DROP TABLE tax_group');
        $this->addSql('DROP TABLE tax_rule');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_branch');
        $this->addSql('DROP TABLE user_department');
        $this->addSql('DROP TABLE user_agent');
        $this->addSql('DROP TABLE user_group');
        $this->addSql('DROP TABLE user_notification_preference');
        $this->addSql('DROP TABLE user_token');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
